# TCL File Generated by Component Editor 13.1
# Mon Jun 08 10:28:22 CST 2026
# DO NOT MODIFY


# 
# SRAM_Controller "SRAM_Controller" v1.0
#  2026.06.08.10:28:22
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module SRAM_Controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME SRAM_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME SRAM_Controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SRAM_Controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SRAM_controller.v VERILOG PATH modules/SRAM_controller.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_writedata writedata Input 16
add_interface_port s1 avs_s1_readdata readdata Output 16
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_byteenable byteenable Input 2
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
add_interface_port s1 avs_s1_address address Input 20
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point sram_pin
# 
add_interface sram_pin conduit end
set_interface_property sram_pin associatedClock clock
set_interface_property sram_pin associatedReset ""
set_interface_property sram_pin ENABLED true
set_interface_property sram_pin EXPORT_OF ""
set_interface_property sram_pin PORT_NAME_MAP ""
set_interface_property sram_pin CMSIS_SVD_VARIABLES ""
set_interface_property sram_pin SVD_ADDRESS_GROUP ""

add_interface_port sram_pin SRAM_ADDR export Output 20
add_interface_port sram_pin SRAM_DQ export Bidir 16
add_interface_port sram_pin SRAM_CE_N export Output 1
add_interface_port sram_pin SRAM_OE_N export Output 1
add_interface_port sram_pin SRAM_WE_N export Output 1
add_interface_port sram_pin SRAM_UB_N export Output 1
add_interface_port sram_pin SRAM_LB_N export Output 1


# 
# connection point verilog_pin
# 
add_interface verilog_pin conduit end
set_interface_property verilog_pin associatedClock clock
set_interface_property verilog_pin associatedReset ""
set_interface_property verilog_pin ENABLED true
set_interface_property verilog_pin EXPORT_OF ""
set_interface_property verilog_pin PORT_NAME_MAP ""
set_interface_property verilog_pin CMSIS_SVD_VARIABLES ""
set_interface_property verilog_pin SVD_ADDRESS_GROUP ""

add_interface_port verilog_pin ray_grant export Output 1
add_interface_port verilog_pin sram_rd_data export Output 16
add_interface_port verilog_pin ray_addr export Input 20
add_interface_port verilog_pin ray_req export Input 1

